fail_fast: false
default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit, manual]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format Rust files with rustfmt.
        entry: bash -c 'cargo fmt --all -- --check'
        language: system
        files: \.rs$
        pass_filenames: false
      - id: taplo-fmt
        name: taplo fmt
        description: Format TOML files with taplo.
        entry: bash -c 'taplo fmt --option reorder_keys=true --check'
        language: system
        files: \.toml$
        pass_filenames: false
      - id: cargo-check
        name: cargo check
        description: Check Rust packages for errors.
        entry: bash -c 'cargo check --all'
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        description: Lint Rust sources.
        entry: bash -c 'cargo clippy --all-targets --all-features --tests --benches -- -D warnings'
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-test
        name: cargo test
        description: Run Rust unit tests.
        entry: bash -c 'cargo nextest run --workspace --all-features'
        language: system
        files: \.rs$
        pass_filenames: false
