use serde::Serialize;

#[derive(Clone, Serialize, Debug, PartialEq)]
pub struct PersonalityInfo {
    pub key: &'static str,
    pub name: &'static str,
    pub emoji: &'static str,
    pub title: &'static str,
    pub style: &'static str,
    pub partner: &'static str,
    pub court: &'static str,
    pub quote: &'static str,
    pub funny_desc: &'static str,
}

pub fn get_info(key: &str) -> Option<PersonalityInfo> {
    match key {
        "SHIELD" => Some(PersonalityInfo {
            key: "SHIELD",
            name: "铁壁盾卫",
            emoji: "🛡️",
            title: "人肉挡板·球不过网算我输",
            style: "防守反击，把每一球都救回去，等对手先失误",
            partner: "喜欢和进攻型打，因为你会让他们怀疑人生",
            court: "底线深区宽敞，方便我跑动救球",
            quote: "你打不穿我，你就输了。",
            funny_desc: "你是网球界的“打不死的小强”。对手抡到手酸，你还在底线稳稳回球。你最经典的胜利：对手打了30拍后主动下网，然后蹲在地上喘了五分钟。",
        }),
        "HAMMER" => Some(PersonalityInfo {
            key: "HAMMER",
            name: "狂怒战斧",
            emoji: "🔨",
            title: "人形自走炮·要么ACE要么双误",
            style: "全力进攻，每一拍都想结束这一分",
            partner: "只约暴力对抡，软绵绵的球友请绕道",
            court: "墙要近，球要新，线要65磅以上",
            quote: "犹豫，就会败北。",
            funny_desc: "你的字典里没有“过渡球”这三个字。一发时速180，二发时速179。你的球拍线寿命是按局数计算的。你最大的困惑：为什么别人总是叫我“捡球机”？",
        }),
        "DAGGER" => Some(PersonalityInfo {
            key: "DAGGER",
            name: "影刃刺客",
            emoji: "🗡️",
            title: "球场心机婊·专打回头球",
            style: "节奏多变，放小球、挑高球、切削、穿越，怎么难受怎么打",
            partner: "喜欢打体力怪，因为遛狗很快乐",
            court: "红土最佳，球速慢才有时间想坏点子",
            quote: "跑不死你，我就不是人了。",
            funny_desc: "你是球场上的“导演”，每一分都是你编排的剧本。对手刚冲到网前，你就挑他头顶；对手退到底线，你就放他小球。你的对手赛后通常会问：“能好好打球吗？”",
        }),
        "POTATO" => Some(PersonalityInfo {
            key: "POTATO",
            name: "摆烂地雷",
            emoji: "🥔",
            title: "佛系炸弹·随缘炸到你",
            style: "能不动就不动，偶尔一拍神仙球，其余时间像在散步",
            partner: "等人约，从不主动，打完立刻问吃什么",
            court: "有阴凉、有椅子、有贩卖机、离烧烤摊近",
            quote: "网球诚可贵，烧烤价更高。",
            funny_desc: "你打球的样子像极了周末被迫加班的打工人。移动速度堪比树懒，但偶尔一拍神仙球让所有人目瞪口呆。你的球友永远猜不透你：到底是真的菜，还是在演？",
        }),
        "SWISS_KNIFE" => Some(PersonalityInfo {
            key: "SWISS_KNIFE",
            name: "万能军刀",
            emoji: "🔧",
            title: "啥都会·啥都不精",
            style: "没有明显短板，也没有致命武器，主打一个“随缘切换”",
            partner: "各种球友都能搭，百搭型选手",
            court: "什么场地都能打，但都打不出统治级表现",
            quote: "我不赢你，你也别想轻松赢我。",
            funny_desc: "你是网球界的“瑞士军刀”——功能很多，但没有一个特别好用。你会削球但不够转，你会暴抽但不够快，你会上网但容易漏。你的优势是：对手永远不知道你下一拍会干嘛。",
        }),
        "CHAIN_MACE" => Some(PersonalityInfo {
            key: "CHAIN_MACE",
            name: "狂乱链枷",
            emoji: "⛓️",
            title: "状态过山车·今天战神明天战五渣",
            style: "顺风时神挡杀神，逆风时送分童子",
            partner: "喜欢有观众的场，没人的时候打不起精神",
            court: "灯光要好，观众要多（哪怕只有一个大爷）",
            quote: "我不是不稳定，我是情绪化的艺术家。",
            funny_desc: "你的状态和女朋友的心情一样——完全不可预测。今天你能赢4.0，明天你能输给刚学球的小白。你的球友约你之前都要先问：“今天状态怎么样？”",
        }),
        "LANCE" => Some(PersonalityInfo {
            key: "LANCE",
            name: "冲锋骑枪",
            emoji: "🏇",
            title: "开局王者·续航青铜",
            style: "前3局猛如虎，后3局软如泥",
            partner: "只打一盘，输了就说“今天没热身”",
            court: "必须有空调/阴凉，热了就崩",
            quote: "不是我打不过你，是我要留着命吃烧烤。",
            funny_desc: "你的体能条和共享单车的余额一样——说没就没。第一盘你能跟3.5打得有来有回，第二盘你连2.0都打不过。你打球的真实写照：0-30落后 → 连赢4局 → 5-2领先 → 连输5局。",
        }),
        "KATANA" => Some(PersonalityInfo {
            key: "KATANA",
            name: "禅意太刀",
            emoji: "🗡️",
            title: "不鸣则已·一鸣惊人",
            style: "平时像退休干部，偶尔一拍让你闭嘴",
            partner: "随缘，从不主动约球，但约了就来",
            court: "必须有阴凉，晒太阳会融化",
            quote: "能不打就不打，要打就要赢。",
            funny_desc: "你打球的样子像极了武侠小说里的扫地僧。全场散步，看起来毫无威胁，然后突然一拍穿越打在边线上。你的球友永远在纠结：你到底会不会打球？",
        }),
        _ => None,
    }
}
